//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosElrabia.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplymentDetail
    {
        public int ID { get; set; }
        public int SupplymentID { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public decimal Discount { get; set; }
        public string ProductID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplyment Supplyment { get; set; }
    }
}
